name: Demo

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  quality:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: edgedb/setup-edgedb@v1
      - run: edgedb instance list
      - run: edgedb instance list --json | jq -r '.[].name' | xargs -i edgedb instance destroy --non-interactive --force {}
      - run: edgedb instance list
      - run: edgedb project init --non-interactive --server-start-conf=manual --server-instance=tests
        working-directory: tests
      - run: edgedb instance start tests
        working-directory: tests
      - run: edgedb instance list
      - name: Set up python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'
      - name: Setup edgedb-python
        run: pip install edgedb
      - name: Run tests
        run: python test_edgedb.py
        working-directory: tests
